dist: trusty
sudo: required
install: true
stages:
  - shell check
  - build docker images
env:
  global:
    - GOARCH=amd64
before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
  - sudo apt-get install -y shellcheck

jobs:
  include:

    - stage: shell check
      name: checking syntax of shell script
      script:
        - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}' || true

    - stage: build perf images
      name: build docker image performance
      script:
        - make perfProj

notifications:
  email:
    recipients:
      - sumit_nagal@intuit.com
